# howto - https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal
name: Deploy Dev Portal env

on: 
  workflow_dispatch:
    inputs:
      env_name:
        description: 'env name. accepted values [nonprod, qa]'     
        required: true
        default: 'nonprod'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: generate APIM SAS token
        id: date
        run: |
         echo "::set-output name=apim_date::$(date -d '+1 days' '+%Y-%m-%dT%H:%M:%S.188Z')"

      - name: generate APIM SAS token
        id: generate-apim-sas-token
        run: |
         echo """${{  steps.date.outputs.apim_date }}"""
